const fs = require('fs');

let html = fs.readFileSync('e:/jop/first/index.html', 'utf8');

// Mod 1 & 2: Delivery Area Select and Delivery Fee Display
const addressInputStr = `              <div class="form-group">
                <label for="fAddress">العنوان</label>
                <input
                  type="text"
                  id="fAddress"
                  class="form-control"
                  required
                  placeholder="العنوان بالتفصيل"
                />
              </div>`;

const areaSelectStr = `              <div class="form-group">
                <label for="fArea">📍 اختار منطقتك</label>
                <select
                  id="fArea"
                  class="form-control"
                  required
                  style="background: var(--bg); border: 2px solid var(--border); border-radius: 10px; font-family: 'Tajawal', sans-serif; direction: rtl; padding: 0.75rem 1rem;"
                >
                  <option value="" disabled selected>-- اختار المنطقة --</option>
                  <option value="الشعبية">الشعبية</option>
                  <option value="الشون">الشون</option>
                  <option value="المشحمة">المشحمة</option>
                  <option value="أبو شاهين">أبو شاهين</option>
                  <option value="محب">محب</option>
                </select>
                <div style="display: inline-flex; background: #FDF3E3; border: 1px solid rgba(196,123,43,0.25); color: #C47B2B; font-size: 0.82rem; font-weight: 700; padding: 0.4rem 0.9rem; border-radius: 8px; margin-top: 0.4rem;">
                  🚗 رسوم التوصيل: ٥٠ جنيه لأي منطقة
                </div>
              </div>\n` + addressInputStr;

html = html.replace(addressInputStr, areaSelectStr);

// Mod 4: Update info card in order section
const statusBlockOriginal = `                <div class="status-item">
                  <strong>رسوم التوصيل</strong>
                  <span>حسب المنطقة</span>
                </div>`;
const statusBlockNew = `                <div class="status-item" style="flex-direction: column; align-items: start; gap: 8px;">
                  <span style="font-weight: 700;">✅ رسوم التوصيل ٥٠ جنيه لأي منطقة</span>
                </div>
                <div class="status-item" style="flex-direction: column; align-items: start; gap: 8px; border-bottom: none; padding-bottom: 0;">
                  <span style="font-weight: 700;">✅ المناطق المتاحة: الشعبية، الشون، المشحمة، أبو شاهين، محب</span>
                </div>`;
html = html.replace(statusBlockOriginal, statusBlockNew);

// Notice: In the HTML, there are original lines:
/*
                <div class="status-item">
                  <strong>ساعات العمل</strong>
                  <span>١٢ ظ - ٢ ص</span>
                </div>
*/
// It's line 985. I'll replace it.

// Mod 5: Show more button CSS
const cssInsertPoint = `      @media (max-width: 768px) {`;
const newCss = `      #show-more-btn:hover {
        background: var(--primary) !important;
        color: #fff !important;
        transform: translateY(-2px) !important;
        box-shadow: 0 8px 24px rgba(196, 123, 43, 0.25) !important;
      }
      @media (max-width: 768px) {`;
html = html.replace(cssInsertPoint, newCss);

// Menu Grid button
const menuGridStr = `        <div class="menu-grid" id="menuGrid">
          <!-- Generated by JS -->
        </div>`;
const menuGridNewStr = `        <div class="menu-grid" id="menuGrid">
          <!-- Generated by JS -->
        </div>
        <button id="show-more-btn" style="display: none; margin: 1.5rem auto 0; background: transparent; border: 2px solid var(--primary); color: var(--primary); font-family: 'Tajawal', sans-serif; font-size: 0.95rem; font-weight: 700; padding: 0.8rem 2.5rem; border-radius: 10px; cursor: pointer; transition: all 0.3s ease; letter-spacing: 0.02em;"></button>`;
html = html.replace(menuGridStr, menuGridNewStr);

// Mod 3 & 5: JS logic
// Old submit logic:
const originalSubmit = `      // Form submit
      const form = document.getElementById("orderForm");
      const msg = document.getElementById("successMsg");
      form.addEventListener("submit", (e) => {
        e.preventDefault();
        form.style.display = "none";
        msg.style.display = "block";
      });`;

const newSubmit = `      // Form submit
      const form = document.getElementById("orderForm");
      const msg = document.getElementById("successMsg");
      form.addEventListener("submit", (e) => {
        e.preventDefault();
        const fArea = document.getElementById("fArea");
        if (!fArea || !fArea.value) {
          alert("⚠️ من فضلك اختار منطقة التوصيل");
          return;
        }
        form.style.display = "none";
        msg.style.display = "block";
      });`;
html = html.replace(originalSubmit, newSubmit);

// Old renderMenu
const originalRenderMenu = `      // Render Menu
      const menuGrid = document.getElementById("menuGrid");
      function renderMenu(filter) {
        menuGrid.innerHTML = "";
        const filtered =
          filter === "all"
            ? menuData
            : menuData.filter((i) => i.cat === filter);

        filtered.forEach((item) => {
          const card = document.createElement("div");
          card.className = "menu-card fade-up visible";
          card.innerHTML = \`
      <div class="card-header">
        <div class="menu-emoji">\${item.emoji}</div>
        <div class="card-title-area">
          <h3>\${item.name}</h3>
          <span class="price">\${item.price} جنيه</span>
        </div>
      </div>
      <p>\${item.desc}</p>
      <div class="card-actions">
        \${item.sauce ? '<span class="badge-sauce">صوص اختياري</span>' : "<span></span>"}
        <button class="add-btn" onclick="addToOrder('\${item.name}', '\${item.price}')" aria-label="إضافة للطلب">+</button>
      </div>
    \`;
          menuGrid.appendChild(card);
        });
      }

      // Init
      renderMenu("all");

      // Tabs logic
      const tabs = document.querySelectorAll(".menu-tab");
      tabs.forEach((tab) => {
        tab.addEventListener("click", () => {
          tabs.forEach((t) => t.classList.remove("active"));
          tab.classList.add("active");
          renderMenu(tab.dataset.filter);
        });
      });`;

const newRenderMenu = `      // Render Menu
      const menuGrid = document.getElementById("menuGrid");
      const showMoreBtn = document.getElementById("show-more-btn");
      let menuExpanded = false;

      function renderMenu(filter) {
        menuGrid.innerHTML = "";
        let filtered =
          filter === "all"
            ? menuData
            : menuData.filter((i) => i.cat === filter);

        if (filter === "all") {
          if (!menuExpanded) {
            const remainingCount = filtered.length - 6;
            filtered = filtered.slice(0, 6);
            if (remainingCount > 0) {
              showMoreBtn.innerText = \`🍽️ شوف باقي القائمة كاملة (\${remainingCount} طبق باقي)\`;
              showMoreBtn.style.display = "block";
            } else {
              showMoreBtn.style.display = "none";
            }
          } else {
            showMoreBtn.innerText = "▲ تقليل القائمة";
            showMoreBtn.style.display = "block";
          }
        } else {
          showMoreBtn.style.display = "none";
        }

        filtered.forEach((item) => {
          const card = document.createElement("div");
          card.className = "menu-card fade-up visible";
          card.style.opacity = "0";
          card.style.transform = "translateY(10px)";
          card.style.transition = "opacity 0.3s, transform 0.3s";
          card.innerHTML = \`
      <div class="card-header">
        <div class="menu-emoji">\${item.emoji}</div>
        <div class="card-title-area">
          <h3>\${item.name}</h3>
          <span class="price">\${item.price} جنيه</span>
        </div>
      </div>
      <p>\${item.desc}</p>
      <div class="card-actions">
        \${item.sauce ? '<span class="badge-sauce">صوص اختياري</span>' : "<span></span>"}
        <button class="add-btn" onclick="addToOrder('\${item.name}', '\${item.price}')" aria-label="إضافة للطلب">+</button>
      </div>
    \`;
          menuGrid.appendChild(card);
          
          requestAnimationFrame(() => {
            requestAnimationFrame(() => {
              card.style.opacity = "1";
              card.style.transform = "translateY(0)";
            });
          });
        });
      }

      showMoreBtn.addEventListener("click", () => {
        menuExpanded = !menuExpanded;
        if (menuExpanded) {
          renderMenu('all');
        } else {
          renderMenu('all');
          document.getElementById('menu').scrollIntoView({ behavior: 'smooth' });
        }
      });

      // Init
      renderMenu("all");

      // Tabs logic
      const tabs = document.querySelectorAll(".menu-tab");
      tabs.forEach((tab) => {
        tab.addEventListener("click", () => {
          tabs.forEach((t) => t.classList.remove("active"));
          tab.classList.add("active");
          const filter = tab.dataset.filter;
          if (filter !== "all") {
            menuExpanded = false;
          }
          renderMenu(filter);
        });
      });`;

html = html.replace(originalRenderMenu, newRenderMenu);

fs.writeFileSync('e:/jop/first/index.html', html, 'utf8');
console.log("File saved successfully.");
